FROM golang:1.17-bullseye AS build

# Set destination for COPY
WORKDIR /app


# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy

COPY yb-tools/ /app

WORKDIR /app/yb-tools/yugaware-client/

COPY /yb-tools/yugaware-client/main.go /app/yb-tools/yugaware-client

RUN go build .

ENTRYPOINT ["/app/yb-tools/yugaware-client/yugaware-client"]
